export const LOAD_SETTINGS_PARAMETERS = 'LOAD_SETTINGS_PARAMETERS';
export const SAVE_SETTINGS_PARAMETERS = 'SAVE_SETTINGS_PARAMETERS';

export const SAVE_BODY_PARAMETERS = 'SAVE_BODY_PARAMETERS';
export const LOAD_BODY_PARAMETERS = 'LOAD_BODY_PARAMETERS';